// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Uv5-_zhLpt2d4z6952L84rlrCnd9toE',
    appId: '1:28616092597:web:4ca61f7373ad88da8d47fc',
    messagingSenderId: '28616092597',
    projectId: 'movieapp-52f3c',
    authDomain: 'movieapp-52f3c.firebaseapp.com',
    storageBucket: 'movieapp-52f3c.firebasestorage.app',
    measurementId: 'G-FDJ55DQ04D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1DESAsj74m8eufsNrn9mwV7kI8qBglZY',
    appId: '1:28616092597:android:0438f92c8ba1aa168d47fc',
    messagingSenderId: '28616092597',
    projectId: 'movieapp-52f3c',
    storageBucket: 'movieapp-52f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_IFJvtQ_AlbpLfxdS3B4OtZWdiUYspSQ',
    appId: '1:28616092597:ios:30749c3719ccd9708d47fc',
    messagingSenderId: '28616092597',
    projectId: 'movieapp-52f3c',
    storageBucket: 'movieapp-52f3c.firebasestorage.app',
    iosClientId:
        '28616092597-krqolk2mfekulujb7p4mu455updelnmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_IFJvtQ_AlbpLfxdS3B4OtZWdiUYspSQ',
    appId: '1:28616092597:ios:30749c3719ccd9708d47fc',
    messagingSenderId: '28616092597',
    projectId: 'movieapp-52f3c',
    storageBucket: 'movieapp-52f3c.firebasestorage.app',
    iosClientId:
        '28616092597-krqolk2mfekulujb7p4mu455updelnmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Uv5-_zhLpt2d4z6952L84rlrCnd9toE',
    appId: '1:28616092597:web:27e61392cab2397a8d47fc',
    messagingSenderId: '28616092597',
    projectId: 'movieapp-52f3c',
    authDomain: 'movieapp-52f3c.firebaseapp.com',
    storageBucket: 'movieapp-52f3c.firebasestorage.app',
    measurementId: 'G-C1LM94WJP0',
  );
}
